### ISSUE TITLE
Create a message handler

### ISSUE THREAD

**Issue by Barsik4** [shadowolfyt/shadowBot#3]

**Comment by jasoryeh** [comment]
How do you want it to work

**Comment by Barsik4** [comment]
@jasoryeh basically just for now a handler that can detect, allow commands to be added and loaded into separate files (similar to the eventLoader).

**Comment by jasoryeh** [comment]
I understand now.

**Comment by Barsik4** [comment]
I will attempt to make a draft and test the handler this afternoon.

**Comment by shadowolfyt** [comment]
Fixed with the commit of https://github.com/shadowolfyt/shadowBot/commit/9cc9d019bc98f2a78551ca1e263d05ce49f7d288
Thanks @Barsik4 for the alright attempt.
